name: 'Repo Lockdown'

on:
  pull_request_target:
    types: opened
  schedule:
    - cron: '0 * * * *'

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
          process-only: 'prs'
          pr-comment: >
            This repository does not accept pull requests,
            see the README for details.
          exclude-pr-labels: 'pinned'
